<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Nacionalidade;
use Illuminate\Database\Seeder;

final class NacionalidadesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Nacionalidade::create(
            ['pais' => 'África do Sul', 'nacionalidade' => 'south-africa', 'params' => json_encode(['flag' => 'south-africa'])],
            ['pais' => 'Afeganistão', 'nacionalidade' => 'afghanistan', 'params' => json_encode(['flag' => 'afghanistan'])],
            ['pais' => 'Albania', 'nacionalidade' => 'albania', 'params' => json_encode(['flag' => 'albania'])],
            ['pais' => 'Algeria', 'nacionalidade' => 'algeria', 'params' => json_encode(['flag' => 'algeria'])],
            ['pais' => 'Alemanha', 'nacionalidade' => 'germany', 'params' => json_encode(['flag' => 'germany'])],
            ['pais' => 'Andorra', 'nacionalidade' => 'andorra', 'params' => json_encode(['flag' => 'andorra'])],
            ['pais' => 'Angola', 'nacionalidade' => 'angola', 'params' => json_encode(['flag' => 'angola'])],
            ['pais' => 'Anguilla', 'nacionalidade' => 'anguilla', 'params' => json_encode(['flag' => 'anguilla'])],
            ['pais' => 'Antigua e Barbuda', 'nacionalidade' => 'antigua-and-barbuda', 'params' => json_encode(['flag' => 'antigua-and-barbuda'])],
            ['pais' => 'Arábia-Saudita', 'nacionalidade' => 'saudi-arabia', 'params' => json_encode(['flag' => 'saudi-arabia'])],
            ['pais' => 'Argentina', 'nacionalidade' => 'argentina', 'params' => json_encode(['flag' => 'argentina'])],
            ['pais' => 'Arménia', 'nacionalidade' => 'armenia', 'params' => json_encode(['flag' => 'armenia'])],
            ['pais' => 'Aruba', 'nacionalidade' => 'aruba', 'params' => json_encode(['flag' => 'aruba'])],
            ['pais' => 'Australia', 'nacionalidade' => 'australia', 'params' => json_encode(['flag' => 'australia'])],
            ['pais' => 'Austria', 'nacionalidade' => 'austria', 'params' => json_encode(['flag' => 'austria'])],
            ['pais' => 'Azerbaijão', 'nacionalidade' => 'azerbaijan', 'params' => json_encode(['flag' => 'azerbaijan'])],
            ['pais' => 'Bahamas', 'nacionalidade' => 'bahamas', 'params' => json_encode(['flag' => 'bahamas'])],
            ['pais' => 'Bahrain', 'nacionalidade' => 'bahrain', 'params' => json_encode(['flag' => 'bahrain'])],
            ['pais' => 'Bangladesh', 'nacionalidade' => 'bangladesh', 'params' => json_encode(['flag' => 'bangladesh'])],
            ['pais' => 'Barbados', 'nacionalidade' => 'barbados', 'params' => json_encode(['flag' => 'barbados'])],
            ['pais' => 'Belarus', 'nacionalidade' => 'belarus', 'params' => json_encode(['flag' => 'belarus'])],
            ['pais' => 'Bélgica', 'nacionalidade' => 'belgium', 'params' => json_encode(['flag' => 'belgium'])],
            ['pais' => 'Belize', 'nacionalidade' => 'belize', 'params' => json_encode(['flag' => 'belize'])],
            ['pais' => 'Benin', 'nacionalidade' => 'benin', 'params' => json_encode(['flag' => 'benin'])],
            ['pais' => 'Bermuda', 'nacionalidade' => 'bermuda', 'params' => json_encode(['flag' => 'bermuda'])],
            ['pais' => 'Botão', 'nacionalidade' => 'bhutan', 'params' => json_encode(['flag' => 'bhutan'])],
            ['pais' => 'Bolívia', 'nacionalidade' => 'bolivia', 'params' => json_encode(['flag' => 'bolivia'])],
            ['pais' => 'Bonaire', 'nacionalidade' => 'bonaire', 'params' => json_encode(['flag' => 'bonaire'])],
            ['pais' => 'Bosnia-Herzegovina', 'nacionalidade' => 'bosnia-and-herzegovina', 'params' => json_encode(['flag' => 'bosnia-and-herzegovina'])],
            ['pais' => 'Botswana', 'nacionalidade' => 'botswana', 'params' => json_encode(['flag' => 'botswana'])],
            ['pais' => 'Brasil', 'nacionalidade' => 'brazil', 'params' => json_encode(['flag' => 'brazil'])],
            ['pais' => 'Brunei', 'nacionalidade' => 'brunei', 'params' => json_encode(['flag' => 'brunei'])],
            ['pais' => 'Bulgaria', 'nacionalidade' => 'bulgaria', 'params' => json_encode(['flag' => 'bulgaria'])],
            ['pais' => 'Burkina-Faso', 'nacionalidade' => 'burkina-faso', 'params' => json_encode(['flag' => 'burkina-faso'])],
            ['pais' => 'Burundi', 'nacionalidade' => 'burundi', 'params' => json_encode(['flag' => 'burundi'])],
            ['pais' => 'Cambodia', 'nacionalidade' => 'cambodia', 'params' => json_encode(['flag' => 'cambodia'])],
            ['pais' => 'Camarões', 'nacionalidade' => 'cameroon', 'params' => json_encode(['flag' => 'cameroon'])],
            ['pais' => 'Canadá', 'nacionalidade' => 'canada', 'params' => json_encode(['flag' => 'canada'])],
            ['pais' => 'Cabo Verde', 'nacionalidade' => 'cape-verde', 'params' => json_encode(['flag' => 'cape-verde'])],
            ['pais' => 'Cazaquistão', 'nacionalidade' => 'kazakhstan', 'params' => json_encode(['flag' => 'kazakhstan'])],
            ['pais' => 'Cidade do Vaticano', 'nacionalidade' => 'vatican-city', 'params' => json_encode(['flag' => 'vatican-city'])],
            ['pais' => 'Chad', 'nacionalidade' => 'chad', 'params' => json_encode(['flag' => 'chad'])],
            ['pais' => 'Chile', 'nacionalidade' => 'chile', 'params' => json_encode(['flag' => 'chile'])],
            ['pais' => 'China', 'nacionalidade' => 'china', 'params' => json_encode(['flag' => 'china'])],
            ['pais' => 'Colombia', 'nacionalidade' => 'colombia', 'params' => json_encode(['flag' => 'colombia'])],
            ['pais' => 'Columbia Britânica', 'nacionalidade' => 'british-columbia', 'params' => json_encode(['flag' => 'british-columbia'])],
            ['pais' => 'Comoros', 'nacionalidade' => 'comoros', 'params' => json_encode(['flag' => 'comoros'])],
            ['pais' => 'Coração', 'nacionalidade' => 'curacao', 'params' => json_encode(['flag' => 'curacao'])],
            ['pais' => 'Costa Rica', 'nacionalidade' => 'costa-rica', 'params' => json_encode(['flag' => 'costa-rica'])],
            ['pais' => 'Costa Marfim', 'nacionalidade' => 'ivory-coast', 'params' => json_encode(['flag' => 'ivory-coast'])],
            ['pais' => 'Croácia', 'nacionalidade' => 'croatia', 'params' => json_encode(['flag' => 'croatia'])],
            ['pais' => 'Cuba', 'nacionalidade' => 'cuba', 'params' => json_encode(['flag' => 'cuba'])],
            ['pais' => 'Dinamarca', 'nacionalidade' => 'denmark', 'params' => json_encode(['flag' => 'denmark'])],
            ['pais' => 'Djibouti', 'nacionalidade' => 'djibouti', 'params' => json_encode(['flag' => 'djibouti'])],
            ['pais' => 'Dominica', 'nacionalidade' => 'dominica', 'params' => json_encode(['flag' => 'dominica'])],
            ['pais' => 'Timor Leste', 'nacionalidade' => 'east-timor', 'params' => json_encode(['flag' => 'east-timor'])],
            ['pais' => 'Equador', 'nacionalidade' => 'ecuador', 'params' => json_encode(['flag' => 'ecuador'])],
            ['pais' => 'Egipto', 'nacionalidade' => 'egypt', 'params' => json_encode(['flag' => 'egypt'])],
            ['pais' => 'El Salvador', 'nacionalidade' => 'el-salvador', 'params' => json_encode(['flag' => 'el-salvador'])],
            ['pais' => 'Eritrea', 'nacionalidade' => 'eritrea', 'params' => json_encode(['flag' => 'eritrea'])],
            ['pais' => 'Escócia', 'nacionalidade' => 'scotland', 'params' => json_encode(['flag' => 'scotland'])],
            ['pais' => 'Eslováquia', 'nacionalidade' => 'slovakia', 'params' => json_encode(['flag' => 'slovakia'])],
            ['pais' => 'Eslovénia', 'nacionalidade' => 'slovenia', 'params' => json_encode(['flag' => 'slovenia'])],
            ['pais' => 'Espanha', 'nacionalidade' => 'spain', 'params' => json_encode(['flag' => 'spain'])],
            ['pais' => 'Estonia', 'nacionalidade' => 'estonia', 'params' => json_encode(['flag' => 'estonia'])],
            ['pais' => 'Etiopia', 'nacionalidade' => 'ethiopia', 'params' => json_encode(['flag' => 'ethiopia'])],
            ['pais' => 'Fiji', 'nacionalidade' => 'fiji', 'params' => json_encode(['flag' => 'fiji'])],
            ['pais' => 'Filipinas', 'nacionalidade' => 'philippines', 'params' => json_encode(['flag' => 'philippines'])],
            ['pais' => 'Finlândia', 'nacionalidade' => 'finland', 'params' => json_encode(['flag' => 'finland'])],
            ['pais' => 'França', 'nacionalidade' => 'france', 'params' => json_encode(['flag' => 'france'])],
            ['pais' => 'Gabon', 'nacionalidade' => 'gabon', 'params' => json_encode(['flag' => 'gabon'])],
            ['pais' => 'Gâmbia', 'nacionalidade' => 'gambia', 'params' => json_encode(['flag' => 'gambia'])],
            ['pais' => 'Georgia', 'nacionalidade' => 'georgia', 'params' => json_encode(['flag' => 'georgia'])],
            ['pais' => 'Gana', 'nacionalidade' => 'ghana', 'params' => json_encode(['flag' => 'ghana'])],
            ['pais' => 'Grécia', 'nacionalidade' => 'greece', 'params' => json_encode(['flag' => 'greece'])],
            ['pais' => 'Gronelândia', 'nacionalidade' => 'greenland', 'params' => json_encode(['flag' => 'greenland'])],
            ['pais' => 'Grenada', 'nacionalidade' => 'grenada', 'params' => json_encode(['flag' => 'grenada'])],
            ['pais' => 'Guam', 'nacionalidade' => 'guam', 'params' => json_encode(['flag' => 'guam'])],
            ['pais' => 'Guatemala', 'nacionalidade' => 'guatemala', 'params' => json_encode(['flag' => 'guatemala'])],
            ['pais' => 'Guernsey', 'nacionalidade' => 'guernsey', 'params' => json_encode(['flag' => 'guernsey'])],
            ['pais' => 'Guiné', 'nacionalidade' => 'guinea', 'params' => json_encode(['flag' => 'guinea'])],
            ['pais' => 'Guiné Bissau', 'nacionalidade' => 'guinea-bissau', 'params' => json_encode(['flag' => 'guinea-bissau'])],
            ['pais' => 'Guiné Equatorial', 'nacionalidade' => 'equatorial-guinea', 'params' => json_encode(['flag' => 'equatorial-guinea'])],
            ['pais' => 'Guiné Nova Papua', 'nacionalidade' => 'papua-new-guinea', 'params' => json_encode(['flag' => 'papua-new-guinea'])],
            ['pais' => 'Haiti', 'nacionalidade' => 'haiti', 'params' => json_encode(['flag' => 'haiti'])],
            ['pais' => 'Holanda', 'nacionalidade' => 'netherlands', 'params' => json_encode(['flag' => 'netherlands'])],
            ['pais' => 'Honduras', 'nacionalidade' => 'honduras', 'params' => json_encode(['flag' => 'honduras'])],
            ['pais' => 'Hong-Kong', 'nacionalidade' => 'hong-kong', 'params' => json_encode(['flag' => 'hong-kong'])],
            ['pais' => 'Hungria', 'nacionalidade' => 'hungary', 'params' => json_encode(['flag' => 'hungary'])],
            ['pais' => 'Islandia', 'nacionalidade' => 'iceland', 'params' => json_encode(['flag' => 'iceland'])],
            ['pais' => 'Ilhas Aland', 'nacionalidade' => 'Alander', 'params' => json_encode(['flag' => 'aland-islands'])],
            ['pais' => 'Ilhas Baleares', 'nacionalidade' => 'balearic-islands', 'params' => json_encode(['flag' => 'balearic-islands'])],
            ['pais' => 'Ilhas Caimão', 'nacionalidade' => 'cayman-islands', 'params' => json_encode(['flag' => 'cayman-islands'])],
            ['pais' => 'Ilhas Coco', 'nacionalidade' => 'cocos-island', 'params' => json_encode(['flag' => 'cocos-island'])],
            ['pais' => 'Ilhas Cook', 'nacionalidade' => 'cook-islands', 'params' => json_encode(['flag' => 'cook-islands'])],
            ['pais' => 'Ilhas Falkland', 'nacionalidade' => 'falkland-islands', 'params' => json_encode(['flag' => 'falkland-islands'])],
            ['pais' => 'Ilhas Galapagos', 'nacionalidade' => 'galapagos-islands', 'params' => json_encode(['flag' => 'galapagos-islands'])],
            ['pais' => 'Ilha do Homem', 'nacionalidade' => 'isle-of-man', 'params' => json_encode(['flag' => 'isle-of-man'])],
            ['pais' => 'Ilhas Marshall', 'nacionalidade' => 'marshall-island', 'params' => json_encode(['flag' => 'marshall-island'])],
            ['pais' => 'Ilhas Natal', 'nacionalidade' => 'christmas-island', 'params' => json_encode(['flag' => 'christmas-island'])],
            ['pais' => 'Ilhas Norfolk', 'nacionalidade' => 'norfolk-island', 'params' => json_encode(['flag' => 'norfolk-island'])],
            ['pais' => 'Ilhas Pitcairn', 'nacionalidade' => 'pitcairn-islands', 'params' => json_encode(['flag' => 'pitcairn-islands'])],
            ['pais' => 'Ilhas Saba', 'nacionalidade' => 'saba-island', 'params' => json_encode(['flag' => 'saba-island'])],
            ['pais' => 'Ilhas Salomão', 'nacionalidade' => 'solomon-islands', 'params' => json_encode(['flag' => 'solomon-islands'])],
            ['pais' => 'Ilhas Virgens Britânicas', 'nacionalidade' => 'british-virgin-islands', 'params' => json_encode(['flag' => 'british-virgin-islands'])],
            ['pais' => 'Índia', 'nacionalidade' => 'india', 'params' => json_encode(['flag' => 'india'])],
            ['pais' => 'Indonesia', 'nacionalidade' => 'indonesia', 'params' => json_encode(['flag' => 'indonesia'])],
            ['pais' => 'Inglaterra', 'nacionalidade' => 'england', 'params' => json_encode(['flag' => 'england'])],
            ['pais' => 'Irão', 'nacionalidade' => 'iran', 'params' => json_encode(['flag' => 'iran'])],
            ['pais' => 'Iraque', 'nacionalidade' => 'iraq', 'params' => json_encode(['flag' => 'iraq'])],
            ['pais' => 'Irlanda', 'nacionalidade' => 'ireland', 'params' => json_encode(['flag' => 'ireland'])],
            ['pais' => 'Israel', 'nacionalidade' => 'israel', 'params' => json_encode(['flag' => 'israel'])],
            ['pais' => 'Itália', 'nacionalidade' => 'italy', 'params' => json_encode(['flag' => 'italy'])],
            ['pais' => 'Jamaica', 'nacionalidade' => 'jamaica', 'params' => json_encode(['flag' => 'jamaica'])],
            ['pais' => 'Japão', 'nacionalidade' => 'japan', 'params' => json_encode(['flag' => 'japan'])],
            ['pais' => 'Jersey', 'nacionalidade' => 'jersey', 'params' => json_encode(['flag' => 'jersey'])],
            ['pais' => 'Jordania', 'nacionalidade' => 'jordan', 'params' => json_encode(['flag' => 'jordan'])],
            ['pais' => 'Kenia', 'nacionalidade' => 'kenya', 'params' => json_encode(['flag' => 'kenya'])],
            ['pais' => 'Kiribati', 'nacionalidade' => 'kiribati', 'params' => json_encode(['flag' => 'kiribati'])],
            ['pais' => 'Korea do Norte', 'nacionalidade' => 'north-korea', 'params' => json_encode(['flag' => 'north-korea'])],
            ['pais' => 'Korea do Sul', 'nacionalidade' => 'south-korea', 'params' => json_encode(['flag' => 'south-korea'])],
            ['pais' => 'Kosovo', 'nacionalidade' => 'kosovo', 'params' => json_encode(['flag' => 'kosovo'])],
            ['pais' => 'Kuwait', 'nacionalidade' => 'kuwait', 'params' => json_encode(['flag' => 'kuwait'])],
            ['pais' => 'Kyrgyzstan', 'nacionalidade' => 'kyrgyzstan', 'params' => json_encode(['flag' => 'kyrgyzstan'])],
            ['pais' => 'Laos', 'nacionalidade' => 'laos', 'params' => json_encode(['flag' => 'laos'])],
            ['pais' => 'Latvia', 'nacionalidade' => 'latvia', 'params' => json_encode(['flag' => 'latvia'])],
            ['pais' => 'Libano', 'nacionalidade' => 'lebanon', 'params' => json_encode(['flag' => 'lebanon'])],
            ['pais' => 'Lesotho', 'nacionalidade' => 'lesotho', 'params' => json_encode(['flag' => 'lesotho'])],
            ['pais' => 'Liberia', 'nacionalidade' => 'liberia', 'params' => json_encode(['flag' => 'liberia'])],
            ['pais' => 'Libia', 'nacionalidade' => 'libya', 'params' => json_encode(['flag' => 'libya'])],
            ['pais' => 'Liechtenstein', 'nacionalidade' => 'liechtenstein', 'params' => json_encode(['flag' => 'liechtenstein'])],
            ['pais' => 'Lituânia', 'nacionalidade' => 'lithuania', 'params' => json_encode(['flag' => 'lithuania'])],
            ['pais' => 'Luxemburgo', 'nacionalidade' => 'luxembourg', 'params' => json_encode(['flag' => 'luxembourg'])],
            ['pais' => 'Macau', 'nacionalidade' => 'macao', 'params' => json_encode(['flag' => 'macao'])],
            ['pais' => 'Madagascar', 'nacionalidade' => 'madagascar', 'params' => json_encode(['flag' => 'madagascar'])],
            ['pais' => 'Malawi', 'nacionalidade' => 'malawi', 'params' => json_encode(['flag' => 'malawi'])],
            ['pais' => 'Malásia', 'nacionalidade' => 'malaysia', 'params' => json_encode(['flag' => 'malaysia'])],
            ['pais' => 'Maldivas', 'nacionalidade' => 'maldives', 'params' => json_encode(['flag' => 'maldives'])],
            ['pais' => 'Mali', 'nacionalidade' => 'mali', 'params' => json_encode(['flag' => 'mali'])],
            ['pais' => 'Malta', 'nacionalidade' => 'malta', 'params' => json_encode(['flag' => 'malta'])],
            ['pais' => 'Martinique', 'nacionalidade' => 'martinique', 'params' => json_encode(['flag' => 'martinique'])],
            ['pais' => 'Mauritânia', 'nacionalidade' => 'mauritania', 'params' => json_encode(['flag' => 'mauritania'])],
            ['pais' => 'Mauricias', 'nacionalidade' => 'mauritius', 'params' => json_encode(['flag' => 'mauritius'])],
            ['pais' => 'México', 'nacionalidade' => 'mexico', 'params' => json_encode(['flag' => 'mexico'])],
            ['pais' => 'Micronesia', 'nacionalidade' => 'micronesia', 'params' => json_encode(['flag' => 'micronesia'])],
            ['pais' => 'Marrocos', 'nacionalidade' => 'morocco', 'params' => json_encode(['flag' => 'morocco'])],
            ['pais' => 'Moldova', 'nacionalidade' => 'moldova', 'params' => json_encode(['flag' => 'moldova'])],
            ['pais' => 'Mónaco', 'nacionalidade' => 'monaco', 'params' => json_encode(['flag' => 'monaco'])],
            ['pais' => 'Mongólia', 'nacionalidade' => 'mongolia', 'params' => json_encode(['flag' => 'mongolia'])],
            ['pais' => 'Montenegro', 'nacionalidade' => 'montenegro', 'params' => json_encode(['flag' => 'montenegro'])],
            ['pais' => 'Montserrat', 'nacionalidade' => 'montserrat', 'params' => json_encode(['flag' => 'montserrat'])],
            ['pais' => 'Moçambique', 'nacionalidade' => 'mozambique', 'params' => json_encode(['flag' => 'mozambique'])],
            ['pais' => 'Myanmar', 'nacionalidade' => 'myanmar', 'params' => json_encode(['flag' => 'myanmar'])],
            ['pais' => 'Namibia', 'nacionalidade' => 'namibia', 'params' => json_encode(['flag' => 'namibia'])],
            ['pais' => 'NATO', 'nacionalidade' => 'nato', 'params' => json_encode(['flag' => 'nato'])],
            ['pais' => 'Nauru', 'nacionalidade' => 'nauru', 'params' => json_encode(['flag' => 'nauru'])],
            ['pais' => 'Nepal', 'nacionalidade' => 'nepal', 'params' => json_encode(['flag' => 'nepal'])],
            ['pais' => 'Nova Zelândia', 'nacionalidade' => 'new-zealand', 'params' => json_encode(['flag' => 'new-zealand'])],
            ['pais' => 'Nicaragua', 'nacionalidade' => 'nicaragua', 'params' => json_encode(['flag' => 'nicaragua'])],
            ['pais' => 'Niger', 'nacionalidade' => 'niger', 'params' => json_encode(['flag' => 'niger'])],
            ['pais' => 'Nigeria', 'nacionalidade' => 'nigeria', 'params' => json_encode(['flag' => 'nigeria'])],
            ['pais' => 'Niue', 'nacionalidade' => 'niue', 'params' => json_encode(['flag' => 'niue'])],
            ['pais' => 'Noruega', 'nacionalidade' => 'norway', 'params' => json_encode(['flag' => 'norway'])],
            ['pais' => 'Oman', 'nacionalidade' => 'oman', 'params' => json_encode(['flag' => 'oman'])],
            ['pais' => 'Ossetia', 'nacionalidade' => 'ossetia', 'params' => json_encode(['flag' => 'ossetia'])],
            ['pais' => 'Paquistão', 'nacionalidade' => 'pakistan', 'params' => json_encode(['flag' => 'pakistan'])],
            ['pais' => 'Palau', 'nacionalidade' => 'palau', 'params' => json_encode(['flag' => 'palau'])],
            ['pais' => 'Palestina', 'nacionalidade' => 'palestine', 'params' => json_encode(['flag' => 'palestine'])],
            ['pais' => 'Panamá', 'nacionalidade' => 'panama', 'params' => json_encode(['flag' => 'panama'])],
            ['pais' => 'Paraguai', 'nacionalidade' => 'paraguay', 'params' => json_encode(['flag' => 'paraguay'])],
            ['pais' => 'Peru', 'nacionalidade' => 'peru', 'params' => json_encode(['flag' => 'peru'])],
            ['pais' => 'Polónia', 'nacionalidade' => 'poland', 'params' => json_encode(['flag' => 'poland'])],
            ['pais' => 'Polynesia Francesa', 'nacionalidade' => 'french-polynesia', 'params' => json_encode(['flag' => 'french-polynesia'])],
            ['pais' => 'Portugal', 'nacionalidade' => 'portugal', 'params' => json_encode(['flag' => 'portugal'])],
            ['pais' => 'Porto-Rico', 'nacionalidade' => 'puerto-rico', 'params' => json_encode(['flag' => 'puerto-rico'])],
            ['pais' => 'Qatar', 'nacionalidade' => 'qatar', 'params' => json_encode(['flag' => 'qatar'])],
            ['pais' => 'Rapa-Nui', 'nacionalidade' => 'rapa-nui', 'params' => json_encode(['flag' => 'rapa-nui'])],
            ['pais' => 'República Centro Africana', 'nacionalidade' => 'central-african-republic', 'params' => json_encode(['flag' => 'central-african-republic'])],
            ['pais' => 'República Checa', 'nacionalidade' => 'czech-republic', 'params' => json_encode(['flag' => 'czech-republic'])],
            ['pais' => 'República Democrática Arabe-Sahrawi', 'nacionalidade' => 'sahrawi-arab-democratic-republic', 'params' => json_encode(['flag' => 'sahrawi-arab-democratic-republic'])],
            ['pais' => 'República Democrática do Congo', 'nacionalidade' => 'democratic-republic-of-congo', 'params' => json_encode(['flag' => 'democratic-republic-of-congo'])],
            ['pais' => 'República da Macedónia', 'nacionalidade' => 'republic-of-macedonia', 'params' => json_encode(['flag' => 'republic-of-macedonia'])],
            ['pais' => 'República do Congo', 'nacionalidade' => 'republic-of-the-congo', 'params' => json_encode(['flag' => 'republic-of-the-congo'])],
            ['pais' => 'República Dominica', 'nacionalidade' => 'dominican-republic', 'params' => json_encode(['flag' => 'dominican-republic'])],
            ['pais' => 'Roménia', 'nacionalidade' => 'romania', 'params' => json_encode(['flag' => 'romania'])],
            ['pais' => 'Rússia', 'nacionalidade' => 'russia', 'params' => json_encode(['flag' => 'russia'])],
            ['pais' => 'Rwanda', 'nacionalidade' => 'rwanda', 'params' => json_encode(['flag' => 'rwanda'])],
            ['pais' => 'Samoa', 'nacionalidade' => 'samoa', 'params' => json_encode(['flag' => 'samoa'])],
            ['pais' => 'Samoa Americana', 'nacionalidade' => 'american-samoa', 'params' => json_encode(['flag' => 'american-samoa'])],
            ['pais' => 'São Marino', 'nacionalidade' => 'san-marino', 'params' => json_encode(['flag' => 'san-marino'])],
            ['pais' => 'São Tomé e Prince', 'nacionalidade' => 'sao-tome-and-prince', 'params' => json_encode(['flag' => 'sao-tome-and-prince'])],
            ['pais' => 'Senegal', 'nacionalidade' => 'senegal', 'params' => json_encode(['flag' => 'senegal'])],
            ['pais' => 'Sérvia', 'nacionalidade' => 'serbia', 'params' => json_encode(['flag' => 'serbia'])],
            ['pais' => 'Seychelles', 'nacionalidade' => 'seychelles', 'params' => json_encode(['flag' => 'seychelles'])],
            ['pais' => 'Serra-Leoa', 'nacionalidade' => 'sierra-leone', 'params' => json_encode(['flag' => 'sierra-leone'])],
            ['pais' => 'Singapura', 'nacionalidade' => 'singapore', 'params' => json_encode(['flag' => 'singapore'])],
            ['pais' => 'Somália', 'nacionalidade' => 'somalia', 'params' => json_encode(['flag' => 'somalia'])],
            ['pais' => 'Somaliland', 'nacionalidade' => 'somaliland', 'params' => json_encode(['flag' => 'somaliland'])],
            ['pais' => 'Sudão do Sul', 'nacionalidade' => 'south-sudan', 'params' => json_encode(['flag' => 'south-sudan'])],
            ['pais' => 'Sri-Lanka', 'nacionalidade' => 'sri-lanka', 'params' => json_encode(['flag' => 'sri-lanka'])],
            ['pais' => 'São Barts', 'nacionalidade' => 'st-barts', 'params' => json_encode(['flag' => 'st-barts'])],
            ['pais' => 'Santa Lucia', 'nacionalidade' => 'st-lucia', 'params' => json_encode(['flag' => 'st-lucia'])],
            ['pais' => 'São Vicente e as Grenadines', 'nacionalidade' => 'st-vincent-and-the-grenadines', 'params' => json_encode(['flag' => 'st-vincent-and-the-grenadines'])],
            ['pais' => 'Sudão', 'nacionalidade' => 'sudan', 'params' => json_encode(['flag' => 'sudan'])],
            ['pais' => 'Suriname', 'nacionalidade' => 'suriname', 'params' => json_encode(['flag' => 'suriname'])],
            ['pais' => 'Swaziland', 'nacionalidade' => 'swaziland', 'params' => json_encode(['flag' => 'swaziland'])],
            ['pais' => 'Suécia', 'nacionalidade' => 'sweden', 'params' => json_encode(['flag' => 'sweden'])],
            ['pais' => 'Suíça', 'nacionalidade' => 'switzerland', 'params' => json_encode(['flag' => 'switzerland'])],
            ['pais' => 'Síria', 'nacionalidade' => 'syria', 'params' => json_encode(['flag' => 'syria'])],
            ['pais' => 'Taiwan', 'nacionalidade' => 'taiwan', 'params' => json_encode(['flag' => 'taiwan'])],
            ['pais' => 'Tajiquistão', 'nacionalidade' => 'tajikistan', 'params' => json_encode(['flag' => 'tajikistan'])],
            ['pais' => 'Tanzania', 'nacionalidade' => 'tanzania', 'params' => json_encode(['flag' => 'tanzania'])],
            ['pais' => 'Thailand', 'nacionalidade' => 'thailand', 'params' => json_encode(['flag' => 'thailand'])],
            ['pais' => 'Tibet', 'nacionalidade' => 'tibet', 'params' => json_encode(['flag' => 'tibet'])],
            ['pais' => 'Togo', 'nacionalidade' => 'togo', 'params' => json_encode(['flag' => 'togo'])],
            ['pais' => 'Tokelau', 'nacionalidade' => 'tokelau', 'params' => json_encode(['flag' => 'tokelau'])],
            ['pais' => 'Tonga', 'nacionalidade' => 'tonga', 'params' => json_encode(['flag' => 'tonga'])],
            ['pais' => 'Transnistria', 'nacionalidade' => 'transnistria', 'params' => json_encode(['flag' => 'transnistria'])],
            ['pais' => 'Trinidade-e-Tobago', 'nacionalidade' => 'trinidad-and-tobago', 'params' => json_encode(['flag' => 'trinidad-and-tobago'])],
            ['pais' => 'Tunisia', 'nacionalidade' => 'tunisia', 'params' => json_encode(['flag' => 'tunisia'])],
            ['pais' => 'Turquia', 'nacionalidade' => 'turkey', 'params' => json_encode(['flag' => 'turkey'])],
            ['pais' => 'Turcomenistão', 'nacionalidade' => 'turkmenistan', 'params' => json_encode(['flag' => 'turkmenistan'])],
            ['pais' => 'Tuvalu', 'nacionalidade' => 'tuvalu', 'params' => json_encode(['flag' => 'tuvalu'])],
            ['pais' => 'Ucrânia', 'nacionalidade' => 'ukraine', 'params' => json_encode(['flag' => 'ukraine'])],
            ['pais' => 'Uganda', 'nacionalidade' => 'uganda', 'params' => json_encode(['flag' => 'uganda'])],
            ['pais' => 'Emirates Arabes Unidos', 'nacionalidade' => 'united-arab-emirates', 'params' => json_encode(['flag' => 'united-arab-emirates'])],
            ['pais' => 'União Europeia', 'nacionalidade' => 'european-union', 'params' => json_encode(['flag' => 'european-union'])],
            ['pais' => 'Reino Unido', 'nacionalidade' => 'united-kingdom', 'params' => json_encode(['flag' => 'united-kingdom'])],
            ['pais' => 'Nações Unidas', 'nacionalidade' => 'united-nations', 'params' => json_encode(['flag' => 'united-nations'])],
            ['pais' => 'Estados Unidos', 'nacionalidade' => 'united-states', 'params' => json_encode(['flag' => 'united-states'])],
            ['pais' => 'Uruguai', 'nacionalidade' => 'uruguay', 'params' => json_encode(['flag' => 'uruguay'])],
            ['pais' => 'Usbequistão', 'nacionalidade' => 'uzbekistan', 'params' => json_encode(['flag' => 'uzbekistan'])],
            ['pais' => 'Vanuatu', 'nacionalidade' => 'vanuatu', 'params' => json_encode(['flag' => 'vanuatu'])],
            ['pais' => 'Venezuela', 'nacionalidade' => 'venezuela', 'params' => json_encode(['flag' => 'venezuela'])],
            ['pais' => 'Vietnam', 'nacionalidade' => 'vietnam', 'params' => json_encode(['flag' => 'vietnam'])],
            ['pais' => 'Virgin Islands', 'nacionalidade' => 'virgin-islands', 'params' => json_encode(['flag' => 'virgin-islands'])],
            ['pais' => 'Yemen', 'nacionalidade' => 'yemen', 'params' => json_encode(['flag' => 'yemen'])],
            ['pais' => 'Zambia', 'nacionalidade' => 'zambia', 'params' => json_encode(['flag' => 'zambia'])],
            ['pais' => 'Zimbabwe', 'nacionalidade' => 'zimbabwe', 'params' => json_encode(['flag' => 'zimbabwe'])],
        );

    }
}
